WINDOW_WDT = 130
WINDOW_HGT = 130
WINDOW_TITLE = 'Xonix'


BLOCK_SIZE = 2

FIELD_WDT = 40 * BLOCK_SIZE
FIELD_Y_OFF = 24
FIELD_HGT = 28 * BLOCK_SIZE
FIELD_COL = 3
BORDER_THICKNESS = 2 * BLOCK_SIZE

PLAYER_COL = 1
TAIL_COL = 8
ENEMY_COL = 7
