WINDOW_WDT = 130
WINDOW_HGT = 130
WINDOW_TITLE = 'Xonix'


BLOCK_SIZE = 2

FIELD_WDT = 65 * BLOCK_SIZE
FIELD_Y_OFF = 38
FIELD_HGT = 46 * BLOCK_SIZE
BORDER_THICKNESS = 2 * BLOCK_SIZE

BACKGROUND_COL = 1
FIELD_COL = 2
PLAYER_COL = 3
TAIL_COL = 4
ENEMY_COL = 5
TEXT1_COL = 6
TEXT2_COL = 7
